Tutorial modularization
trav-d13/k_voice_assistant pull request #4
Opened 2023-02-23 16:08 UTC by trav-d13

The tutorial was modularized which should enable us to add skills and functionality to the assistant. 

Additionally all method are documented. 

Please build and test your side before approving to check the docs and the assistant is working for you

2023-02-23 17:36 UTC, ericbanzuzi commented on README.md
> +2. If you have added any additional files in any directory, run the respective command below:
should this (2.) still be in here? you removed it in the previous PR

2023-02-23 17:36 UTC, ericbanzuzi commented on k_assist.yml
> +  - speechrecognition
can you move these (after python) inside pip so it works for me as well, like this:
- pip:
  - speechrecognition
  - wikipedia
  - pyjokes
  - sphinx
  - sphinxcontrib-napoleon
  - sphinx_rtd_theme
  - sphinx-autodoc-typehints
  - pyaudio

2023-02-23 17:38 UTC, ericbanzuzi requested changes
looks good and is working for me except the k_assist.yml, I left a few comments how this could be fixed (it worked for me).

2023-02-24 09:09 UTC, trav-d13 commented on README.md
> +2. If you have added any additional files in any directory, run the respective command below:
Yeah, I thought it wasn't in the prev PR, but it adds the new files into the docs

2023-02-24 09:42 UTC, trav-d13 commented on k_assist.yml
> +  - speechrecognition
I just made the changes, but am getting errors my side. How are you trying to create the environment?

2023-02-24 09:59 UTC, trav-d13 commented on k_assist.yml
> +  - speechrecognition
Fixed

2023-02-24 10:05 UTC, ericbanzuzi approved these changes
Everything works fine now!

2023-02-24 10:06 UTC, merged