Added :
trav-d13/k_voice_assistant pull request #6
Opened 2023-02-25 12:53 UTC by GUNELIS

- FFT file
- librosa and numpy to yml file

2023-02-27 18:45 UTC, trav-d13 commented
To avoid merge conflicts, will you update your branch with main and put the FFT file in the voice directory?

2023-02-28 11:15 UTC, ovmo requested changes
k_assist.yml: 
sphinx_rtd_themer has added *R* at the end, could you remove that before merging?

2023-02-28 12:29 UTC, ovmo approved these changes

2023-02-28 22:55 UTC, ericbanzuzi approved these changes

2023-02-28 22:57 UTC, merged